import type { MerchantTemplate } from "../types";

export const genericTemplates: MerchantTemplate[] = [
  {
    merchantKey: "best_buy",
    plaidMerchantName: "Best Buy",
    nameVariants: ["BEST BUY #1234", "BESTBUY.COM"],
    normalizedResult: "best buy",
    expectedEarnCategory: "shopping_instore",
    plaidCategoryPrimary: "SHOPS",
    plaidCategoryDetailed: "SHOPS_ELECTRONICS",
    matchesBenefitPatterns: ["best buy"],
    amountRange: { min: 20, max: 500 },
  },

  {
    merchantKey: "cvs_pharmacy",
    plaidMerchantName: "CVS",
    nameVariants: ["CVS/PHARMACY #1234", "CVS STORE"],
    normalizedResult: "cvs",
    expectedEarnCategory: "drugstores",
    plaidCategoryPrimary: "SHOPS",
    plaidCategoryDetailed: "SHOPS_PHARMACIES",
    matchesBenefitPatterns: [],
    amountRange: { min: 5, max: 60 },
  },

  {
    merchantKey: "home_depot",
    plaidMerchantName: "Home Depot",
    nameVariants: ["HOME DEPOT #1234", "THE HOME DEPOT"],
    normalizedResult: "home depot",
    expectedEarnCategory: "home_improvement",
    plaidCategoryPrimary: "SHOPS",
    plaidCategoryDetailed: "SHOPS_HARDWARE_STORE",
    matchesBenefitPatterns: [],
    amountRange: { min: 15, max: 300 },
  },

  {
    merchantKey: "starbucks",
    plaidMerchantName: "Starbucks",
    nameVariants: ["STARBUCKS #12847", "STARBUCKS STORE"],
    normalizedResult: "starbucks",
    expectedEarnCategory: "coffee",
    plaidCategoryPrimary: "FOOD_AND_DRINK",
    plaidCategoryDetailed: "FOOD_AND_DRINK_COFFEE",
    matchesBenefitPatterns: [],
    amountRange: { min: 4, max: 12 },
  },

  {
    merchantKey: "instacart",
    plaidMerchantName: "Instacart",
    nameVariants: ["INSTACART", "INSTACART GROCERY"],
    normalizedResult: "instacart",
    expectedEarnCategory: "grocery_online",
    plaidCategoryPrimary: "FOOD_AND_DRINK",
    plaidCategoryDetailed: "FOOD_AND_DRINK_GROCERIES",
    matchesBenefitPatterns: ["instacart"],
    amountRange: { min: 20, max: 150 },
  },

  {
    merchantKey: "dell",
    plaidMerchantName: "Dell",
    nameVariants: ["DELL COMPUTERS", "DELL.COM"],
    normalizedResult: "dell",
    expectedEarnCategory: "shopping_online",
    plaidCategoryPrimary: "SHOPS",
    plaidCategoryDetailed: "SHOPS_DIGITAL_PURCHASE",
    matchesBenefitPatterns: ["dell"],
    amountRange: { min: 50, max: 2000 },
  },

  {
    merchantKey: "adobe",
    plaidMerchantName: "Adobe",
    nameVariants: ["ADOBE CREATIVE CLOUD", "ADOBE.COM"],
    normalizedResult: "adobe",
    expectedEarnCategory: "shopping_online",
    plaidCategoryPrimary: "SHOPS",
    plaidCategoryDetailed: "SHOPS_DIGITAL_PURCHASE",
    matchesBenefitPatterns: ["adobe"],
    amountRange: { min: 19.99, max: 59.99 },
  },

  {
    merchantKey: "car_rental",
    plaidMerchantName: null,
    nameVariants: ["AVIS", "HERTZ", "ENTERPRISE", "NATIONAL"],
    normalizedResult: "avis",
    expectedEarnCategory: "car_rentals",
    plaidCategoryPrimary: "TRANSPORTATION",
    plaidCategoryDetailed: "TRANSPORTATION_CAR_RENTALS",
    matchesBenefitPatterns: ["avis", "hertz", "enterprise", "national car"],
    amountRange: { min: 40, max: 300 },
  },

  {
    merchantKey: "cruise_line",
    plaidMerchantName: null,
    nameVariants: ["CARNIVAL CRUISE", "ROYAL CARIBBEAN", "CRUISE LINE"],
    normalizedResult: "carnival cruise",
    expectedEarnCategory: "travel_other",
    plaidCategoryPrimary: "TRAVEL",
    plaidCategoryDetailed: "TRAVEL_LODGING",
    matchesBenefitPatterns: ["carnival", "royal caribbean", "cruise"],
    amountRange: { min: 500, max: 3000 },
  },

  {
    merchantKey: "entertainment",
    plaidMerchantName: null,
    nameVariants: ["LIVE NATION", "TICKETMASTER", "FANDANGO"],
    normalizedResult: "live nation",
    expectedEarnCategory: "entertainment",
    plaidCategoryPrimary: "ENTERTAINMENT",
    plaidCategoryDetailed: "ENTERTAINMENT_EVENTS",
    matchesBenefitPatterns: ["live nation", "ticketmaster", "fandango"],
    amountRange: { min: 30, max: 500 },
  },

  {
    merchantKey: "stubhub",
    plaidMerchantName: "StubHub",
    nameVariants: ["STUBHUB ORDER", "STUBHUB.COM", "VIAGOGO"],
    normalizedResult: "stubhub",
    expectedEarnCategory: "entertainment",
    plaidCategoryPrimary: "ENTERTAINMENT",
    plaidCategoryDetailed: "ENTERTAINMENT_EVENTS",
    matchesBenefitPatterns: ["stubhub", "viagogo"],
    amountRange: { min: 50, max: 500 },
  },

  {
    merchantKey: "telecom",
    plaidMerchantName: null,
    nameVariants: ["AT&T", "VERIZON", "T-MOBILE", "SPRINT"],
    normalizedResult: "at&t",
    expectedEarnCategory: "phone_services",
    plaidCategoryPrimary: "SERVICE",
    plaidCategoryDetailed: "SERVICE_TELECOMMUNICATION_SERVICES",
    matchesBenefitPatterns: ["at&t", "t-mobile", "verizon", "sprint", "wireless"],
    amountRange: { min: 50, max: 150 },
  },

  {
    merchantKey: "job_board",
    plaidMerchantName: "Indeed",
    nameVariants: ["INDEED", "INDEED.COM"],
    normalizedResult: "indeed",
    expectedEarnCategory: "other",
    plaidCategoryPrimary: "SERVICE",
    plaidCategoryDetailed: "SERVICE_OTHER",
    matchesBenefitPatterns: ["indeed"],
    amountRange: { min: 0, max: 500 },
  },

  {
    merchantKey: "campground",
    plaidMerchantName: null,
    nameVariants: ["KOA CAMPGROUND", "CAMPGROUND", "KOA"],
    normalizedResult: "koa campground",
    expectedEarnCategory: "travel_hotels",
    plaidCategoryPrimary: "TRAVEL",
    plaidCategoryDetailed: "TRAVEL_LODGING",
    matchesBenefitPatterns: ["campground", "koa"],
    amountRange: { min: 25, max: 100 },
  },

  {
    merchantKey: "exclusive_dining",
    plaidMerchantName: "Exclusive Tables",
    nameVariants: [
      "EXCLUSIVE TABLES #1234",
      "EXCLUSIVE TABLES",
    ],
    normalizedResult: "exclusive tables",
    expectedEarnCategory: "dining",
    plaidCategoryPrimary: "FOOD_AND_DRINK",
    plaidCategoryDetailed: "FOOD_AND_DRINK_RESTAURANTS",
    matchesBenefitPatterns: ["exclusive tables", "chase dining"],
    amountRange: { min: 50, max: 300 },
  },

  {
    merchantKey: "misc_services",
    plaidMerchantName: null,
    nameVariants: ["PMUSA", "DULLES", "AIRPORT"],
    normalizedResult: "pmusa",
    expectedEarnCategory: "travel_hotels",
    plaidCategoryPrimary: "TRAVEL",
    plaidCategoryDetailed: "TRAVEL_LODGING",
    matchesBenefitPatterns: ["pmusa", "dulles"],
    amountRange: { min: 10, max: 200 },
  },
];
