import type { EarnCategory } from "./types";

export const EARN_CATEGORY_LABELS: Record<EarnCategory, string> = {
  dining: "Dining",
  groceries: "Groceries",
  grocery_online: "Online Grocery",
  food_delivery: "Food Delivery",
  coffee: "Coffee",
  streaming: "Streaming",
  rideshare: "Rideshare",
  travel_flights: "Flights",
  travel_hotels: "Hotels",
  travel_portal: "Travel Portal",
  travel_other: "Other Travel",
  car_rentals: "Car Rentals",
  parking: "Parking & Tolls",
  transit: "Transit",
  gas_stations: "Gas Stations",
  entertainment: "Entertainment",
  fitness: "Fitness",
  shopping_online: "Online Shopping",
  shopping_instore: "In-Store Shopping",
  drugstores: "Drugstores",
  home_improvement: "Home Improvement",
  wholesale_clubs: "Wholesale Clubs",
  phone_services: "Phone & Internet",
  bills_utilities: "Bills & Utilities",
  insurance: "Insurance",
  other: "Other",
};

export const EARN_CATEGORY_ICONS: Record<EarnCategory, string> = {
  dining: "utensils",
  groceries: "shopping-cart",
  grocery_online: "shopping-basket",
  food_delivery: "truck",
  coffee: "coffee",
  streaming: "tv",
  rideshare: "car",
  travel_flights: "plane",
  travel_hotels: "building",
  travel_portal: "globe",
  travel_other: "map",
  car_rentals: "car",
  parking: "circle-parking",
  transit: "train-front",
  gas_stations: "fuel",
  entertainment: "ticket",
  fitness: "dumbbell",
  shopping_online: "package",
  shopping_instore: "store",
  drugstores: "pill",
  home_improvement: "hammer",
  wholesale_clubs: "warehouse",
  phone_services: "phone",
  bills_utilities: "zap",
  insurance: "shield",
  other: "circle-dot",
};
