export interface PerkCellValue {
  value: string | null;
  isBest?: boolean;
  detail?: string;
  footnote?: boolean;
}

export interface PerkRow {
  label: string;
  tracked: boolean;
  isTotalRow?: boolean;
  cards: Record<string, PerkCellValue>;
}

export interface PerkSection {
  sectionId: string;
  label: string;
  tracked: boolean;
  rows: PerkRow[];
}

export const PERK_SECTIONS: PerkSection[] = [
  {
    sectionId: "benefits",
    label: "Benefits",
    tracked: true,
    rows: [
      {
        label: "Travel benefit",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$300", detail: "per anniversary year" },
          amex_platinum: { value: "$200", detail: "airline fee credit per calendar year" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "$100", detail: "hotel credit per anniversary year" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "$300", detail: "Capital One Travel portal, per anniversary year" },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: "$50", detail: "airline credit, anniversary year" },
          amex_business_platinum: { value: "$600", detail: "$600/yr FHR/THC + $219 CLEAR + $120 Global Entry" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "$150", detail: "Delta Stays credit, calendar year" },
          hilton_aspire: { value: "$400", detail: "Hilton resort + $200 flight credit" },
          ihg_premier: { value: "$50", detail: "United TravelBank cash, calendar year" },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: "$100", detail: "United TravelBank, after $10K spend/yr" },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Dining benefit",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$300", detail: "Exclusive Tables, semi-annual" },
          amex_platinum: { value: "$400", detail: "Resy ($100/quarter)", isBest: true },
          amex_gold: { value: "$220", detail: "$10/mo at select merchants + $50/semi Resy", footnote: true },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "$120", detail: "Resy credit ($10/mo)" },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "DoorDash",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$300", detail: "$5 restaurant + 2x$10 non-restaurant/mo" },
          amex_platinum: { value: null },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "$120", detail: "$10/mo non-restaurant" },
          chase_freedom_flex: { value: "~$70", detail: "DashPass + quarterly promos" },
          chase_freedom_unlimited: { value: "~$60", detail: "6mo DashPass" },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Rideshare",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$120", detail: "Lyft Pink" },
          amex_platinum: { value: "$320", detail: "$200/yr Uber Cash + $120 Uber One", isBest: true },
          amex_gold: { value: "$120", detail: "Uber Cash ($10/mo)", footnote: true },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "$120", detail: "$10/mo U.S. rideshare credit" },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: "$60", detail: "airport rideshare credit" },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Events",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$300", detail: "StubHub credit" },
          amex_platinum: { value: null },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Streaming",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "~$250", detail: "Apple Music/TV+" },
          amex_platinum: { value: "$300", detail: "Digital entertainment ($25/mo)", isBest: true },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: "$120", detail: "Disney streaming ($10/mo)" },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: "$84", detail: "Disney streaming ($7/mo)" },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Fitness",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$120", detail: "Peloton credit" },
          amex_platinum: { value: "$300", detail: "Equinox credit", isBest: true },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Hotel",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "$750", detail: "Edit + Select hotels" },
          amex_platinum: { value: "$600", detail: "FHR/THC ($300/half)" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "$300", detail: "Citi Travel portal, 2+ night stay" },
          citi_strata_premier: { value: "$100", detail: "Citi Travel portal, $500+ booking" },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "$400", detail: "Bilt Travel portal ($200/half)" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "$600", detail: "FHR/THC ($300/half)" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: "$400", detail: "Hilton resort credit ($200/half)" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Shopping",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "$300", detail: "lululemon ($75/qtr); Saks credit ended 7/2026", isBest: true },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "$150", detail: "Dell credit" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: "$120", detail: "Instacart credit" },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Coffee",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: null },
          amex_gold: { value: "$84", detail: "Dunkin' ($7/mo)" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Total tracked benefits",
        tracked: true,
        isTotalRow: true,
        cards: {
          chase_sapphire_reserve: { value: "$2,060" },
          amex_platinum: { value: "$2,760", detail: "Saks ended 7/2026; CLEAR now $219", isBest: true },
          amex_gold: { value: "$424" },
          amex_blue_cash_preferred: { value: "$120", detail: "Disney streaming ($10/mo)" },
          chase_sapphire_preferred: { value: "$340", detail: "incl. $100 hotel credit (2026 refresh)" },
          chase_freedom_flex: { value: "~$70", detail: "6mo DashPass trial + $10/qtr DoorDash" },
          chase_freedom_unlimited: { value: "~$70", detail: "6mo DashPass trial + $10/qtr DoorDash" },
          citi_strata_elite: { value: "$300", detail: "$300 hotel credit" },
          citi_strata_premier: { value: "$100", detail: "$100 hotel credit" },
          capital_one_venture_x: { value: "$400", detail: "$300 travel + $100 anniversary miles" },
          capital_one_venture: { value: "$0", detail: "Value is in 2x flat rate" },
          robinhood_gold: { value: "$0", detail: "Value is in 3x earning rate" },
          bilt_palladium: { value: "$600", detail: "$400 hotel + $200 Bilt Cash annual" },
          amex_blue_cash_everyday: { value: "$264", detail: "Disney ($84) + Home Chef ($180)" },
          citi_custom_cash: { value: "$0", detail: "Value is in 5% auto-select" },
          citi_double_cash: { value: "$0", detail: "Value is in 2% flat rate" },
          discover_it_cash_back: { value: "$0", detail: "Value is in rotating 5% + Year 1 match" },
          us_bank_altitude_connect: { value: "$25", detail: "Global Entry ($100/4yr)" },
          wells_fargo_active_cash: { value: "$0", detail: "Value is in 2% flat rate" },
          wells_fargo_autograph_journey: { value: "$50", detail: "Airline credit" },
          amex_business_platinum: { value: "$1,560", detail: "$600 FHR/THC + $219 CLEAR + $150 Dell + $120 Global Entry" },
          apple_card: { value: "$0", detail: "Value is in 1-3% earning rates" },
          capital_one_savor: { value: "$0", detail: "Value is in 3% categories" },
          delta_platinum: { value: "$390", detail: "$150 Delta Stays + $120 Resy + $120 rideshare" },
          hilton_aspire: { value: "$819", detail: "$400 resort + $200 flight + $219 CLEAR" },
          ihg_premier: { value: "$80", detail: "GE ($120/4yr) + $50 United TravelBank" },
          ink_business_preferred: { value: "$120", detail: "$10/mo DoorDash credit + DashPass" },
          southwest_priority: { value: "$0", detail: "Travel credit ended 12/2025" },
          united_explorer: { value: "$280", detail: "$100 TravelBank + $60 rideshare + $120 Instacart" },
          world_of_hyatt: { value: "$0", detail: "Value is in 4x earning rate" },
        },
      },
    ],
  },
  {
    sectionId: "points",
    label: "Points Earning",
    tracked: true,
    rows: [
      {
        label: "Dining",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "3x" },
          amex_platinum: { value: "1x" },
          amex_gold: { value: "4x", isBest: true },
          amex_blue_cash_preferred: { value: "1%" },
          chase_sapphire_preferred: { value: "3x" },
          chase_freedom_flex: { value: "3x" },
          chase_freedom_unlimited: { value: "3x" },
          citi_strata_elite: { value: "3x", detail: "6x Fri/Sat nights" },
          citi_strata_premier: { value: "3x" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "1%" },
          citi_custom_cash: { value: "1x", detail: "up to 5% auto-select" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%" },
          us_bank_altitude_connect: { value: "2x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "3x" },
          amex_business_platinum: { value: "1x" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "3%" },
          delta_platinum: { value: "2x" },
          hilton_aspire: { value: "3x" },
          ihg_premier: { value: "5x" },
          ink_business_preferred: { value: "1x" },
          southwest_priority: { value: "2x" },
          united_explorer: { value: "2x" },
          world_of_hyatt: { value: "2x" },
        },
      },
      {
        label: "Groceries",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "1x" },
          amex_platinum: { value: "1x" },
          amex_gold: { value: "4x", isBest: true, detail: "cap $25K/yr" },
          amex_blue_cash_preferred: { value: "6%", isBest: true, detail: "cap $6K/yr, then 1%" },
          chase_sapphire_preferred: { value: "1x" },
          chase_freedom_flex: { value: "1x" },
          chase_freedom_unlimited: { value: "1.5x" },
          citi_strata_elite: { value: "1.5x" },
          citi_strata_premier: { value: "3x" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "3%", detail: "cap $6K/yr" },
          citi_custom_cash: { value: "1x", detail: "up to 5% auto-select" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%" },
          us_bank_altitude_connect: { value: "2x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "1x" },
          amex_business_platinum: { value: "1x" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "3%" },
          delta_platinum: { value: "2x" },
          hilton_aspire: { value: "3x" },
          ihg_premier: { value: "3x" },
          ink_business_preferred: { value: "1x" },
          southwest_priority: { value: "1x" },
          united_explorer: { value: "1x" },
          world_of_hyatt: { value: "1x" },
        },
      },
      {
        label: "Travel (direct)",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "4x" },
          amex_platinum: { value: "5x", isBest: true, detail: "flights only" },
          amex_gold: { value: "3x", detail: "flights only" },
          amex_blue_cash_preferred: { value: "1%", detail: "3% ground transit/gas; flights excluded" },
          chase_sapphire_preferred: { value: "2x" },
          chase_freedom_flex: { value: "1x" },
          chase_freedom_unlimited: { value: "1.5x" },
          citi_strata_elite: { value: "1.5x" },
          citi_strata_premier: { value: "3x", detail: "flights only" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "1%" },
          citi_custom_cash: { value: "1x", detail: "up to 5% auto-select" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%" },
          us_bank_altitude_connect: { value: "4x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "4-5x", detail: "5x hotels, 4x flights" },
          amex_business_platinum: { value: "5x", detail: "flights only" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "1x" },
          delta_platinum: { value: "3x" },
          hilton_aspire: { value: "7x" },
          ihg_premier: { value: "5x" },
          ink_business_preferred: { value: "3x", detail: "travel/shipping/internet/phone capped" },
          southwest_priority: { value: "4x", detail: "Southwest purchases" },
          united_explorer: { value: "3x", detail: "United purchases" },
          world_of_hyatt: { value: "2x" },
        },
      },
      {
        label: "Travel (portal)",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "8x" },
          amex_platinum: { value: "5x", detail: "hotels via AmexTravel" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "5x" },
          chase_freedom_flex: { value: "5x" },
          chase_freedom_unlimited: { value: "5x" },
          citi_strata_elite: { value: "12x", isBest: true, detail: "hotels; 6x flights" },
          citi_strata_premier: { value: "10x", detail: "hotels/cars; 3x flights" },
          capital_one_venture_x: { value: "10x", detail: "hotels; 5x flights" },
          capital_one_venture: { value: "5x", detail: "hotels/rentals; 2x flights" },
          robinhood_gold: { value: "5x", detail: "cap $3,500/yr" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "5x", detail: "US Bank Rewards Center" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "5x", detail: "via AmexTravel" },
          apple_card: { value: null },
          capital_one_savor: { value: "5x", detail: "entertainment portal; 8x entertainment portal" },
          delta_platinum: { value: null },
          hilton_aspire: { value: "14x" },
          ihg_premier: { value: "10x" },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: "4x" },
        },
      },
      {
        label: "Streaming",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "1x" },
          amex_platinum: { value: "1x" },
          amex_gold: { value: "1x" },
          amex_blue_cash_preferred: { value: "6%", isBest: true },
          chase_sapphire_preferred: { value: "3x" },
          chase_freedom_flex: { value: "1x" },
          chase_freedom_unlimited: { value: "1.5x" },
          citi_strata_elite: { value: "1.5x" },
          citi_strata_premier: { value: "1x" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "1%" },
          citi_custom_cash: { value: "1x", detail: "up to 5% auto-select" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%" },
          us_bank_altitude_connect: { value: "2x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "1x" },
          amex_business_platinum: { value: "1x" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "3%" },
          delta_platinum: { value: "1x" },
          hilton_aspire: { value: "3x" },
          ihg_premier: { value: "3x" },
          ink_business_preferred: { value: "1x" },
          southwest_priority: { value: "1x" },
          united_explorer: { value: "1x" },
          world_of_hyatt: { value: "1x" },
        },
      },
      {
        label: "Rideshare (Lyft)",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "5x", isBest: true },
          amex_platinum: { value: "1x" },
          amex_gold: { value: "1x" },
          amex_blue_cash_preferred: { value: "3%" },
          chase_sapphire_preferred: { value: "5x", isBest: true },
          chase_freedom_flex: { value: "1x" },
          chase_freedom_unlimited: { value: "1.5x" },
          citi_strata_elite: { value: "1.5x" },
          citi_strata_premier: { value: "1x" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x" },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "1%" },
          citi_custom_cash: { value: "1x", detail: "up to 5% auto-select" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%" },
          us_bank_altitude_connect: { value: "1x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "1x" },
          amex_business_platinum: { value: "1x" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "1x" },
          delta_platinum: { value: "1x" },
          hilton_aspire: { value: "1x" },
          ihg_premier: { value: "1x" },
          ink_business_preferred: { value: "5x", detail: "via Lyft" },
          southwest_priority: { value: "1x" },
          united_explorer: { value: "1x" },
          world_of_hyatt: { value: "2x" },
        },
      },
      {
        label: "Base rate",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "1x" },
          amex_platinum: { value: "1x" },
          amex_gold: { value: "1x" },
          amex_blue_cash_preferred: { value: "1%" },
          chase_sapphire_preferred: { value: "1x" },
          chase_freedom_flex: { value: "1x", detail: "5% rotating quarterly" },
          chase_freedom_unlimited: { value: "1.5x" },
          citi_strata_elite: { value: "1.5x" },
          citi_strata_premier: { value: "1x" },
          capital_one_venture_x: { value: "2x" },
          capital_one_venture: { value: "2x" },
          robinhood_gold: { value: "3x", isBest: true },
          bilt_palladium: { value: "2x" },
          amex_blue_cash_everyday: { value: "1%" },
          citi_custom_cash: { value: "1x", detail: "5% on top category/cycle" },
          citi_double_cash: { value: "2x" },
          discover_it_cash_back: { value: "1%", detail: "5% rotating quarterly" },
          us_bank_altitude_connect: { value: "1x" },
          wells_fargo_active_cash: { value: "2%" },
          wells_fargo_autograph_journey: { value: "1x" },
          amex_business_platinum: { value: "1x" },
          apple_card: { value: "1%", detail: "2% on Apple Pay" },
          capital_one_savor: { value: "1%" },
          delta_platinum: { value: "1x" },
          hilton_aspire: { value: "3x" },
          ihg_premier: { value: "3x" },
          ink_business_preferred: { value: "1x" },
          southwest_priority: { value: "1x" },
          united_explorer: { value: "1x" },
          world_of_hyatt: { value: "1x" },
        },
      },
      {
        label: "Point value",
        tracked: true,
        cards: {
          chase_sapphire_reserve: { value: "1.0\u00A2", detail: "Points Boost up to 2.0\u00A2; 1:1 partners" },
          amex_platinum: { value: "1.0\u00A2" },
          amex_gold: { value: "1.0\u00A2" },
          amex_blue_cash_preferred: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          chase_sapphire_preferred: { value: "1.0\u00A2", detail: "Points Boost up to 1.5\u00A2; Hyatt now 4:3" },
          chase_freedom_flex: { value: "1.0\u00A2", detail: "up to 2.0\u00A2 via CSR/CSP partners" },
          chase_freedom_unlimited: { value: "1.0\u00A2", detail: "up to 2.0\u00A2 via CSR/CSP partners" },
          citi_strata_elite: { value: "1.0\u00A2", detail: "up to 1.9\u00A2 via partners" },
          citi_strata_premier: { value: "1.0\u00A2", detail: "up to 1.9\u00A2 via partners" },
          capital_one_venture_x: { value: "1.0\u00A2", detail: "up to 1.85\u00A2 via partners" },
          capital_one_venture: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 via partners" },
          robinhood_gold: { value: "1.0\u00A2", detail: "fixed 1:1 to brokerage" },
          bilt_palladium: { value: "1.5\u00A2", isBest: true, detail: "up to 2.2\u00A2 via partners" },
          amex_blue_cash_everyday: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          citi_custom_cash: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 via Strata partners" },
          citi_double_cash: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 via Strata partners" },
          discover_it_cash_back: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          us_bank_altitude_connect: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 Real-Time Rewards" },
          wells_fargo_active_cash: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          wells_fargo_autograph_journey: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 via transfer partners" },
          amex_business_platinum: { value: "1.0\u00A2", detail: "up to 2.0\u00A2 via partners" },
          apple_card: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          capital_one_savor: { value: "1.0\u00A2", detail: "cash back, fixed value" },
          delta_platinum: { value: "1.0\u00A2", detail: "up to 1.4\u00A2 via Delta partners" },
          hilton_aspire: { value: "0.5\u00A2", detail: "up to 0.8\u00A2 via partners" },
          ihg_premier: { value: "0.5\u00A2", detail: "up to 0.8\u00A2 via partners" },
          ink_business_preferred: { value: "1.0\u00A2", detail: "up to 2.0\u00A2 via partners" },
          southwest_priority: { value: "1.2\u00A2", detail: "1.2-1.4\u00A2 post-2025 devaluations" },
          united_explorer: { value: "1.0\u00A2", detail: "up to 1.5\u00A2 via partners" },
          world_of_hyatt: { value: "1.5\u00A2", isBest: true, detail: "up to 2.2\u00A2 via partners" },
        },
      },
    ],
  },
  {
    sectionId: "travel_perks",
    label: "Travel Perks",
    tracked: false,
    rows: [
      {
        label: "Airport lounge",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Priority Pass + Sapphire Lounge" },
          amex_platinum: { value: "Centurion + Priority Pass + Delta Sky Club", detail: "1,550+ lounges; Sky Club 10 visits/yr" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Priority Pass Select", detail: "+ 4 Admirals Club passes/yr" },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "Capital One Lounges + Priority Pass", detail: "guest policy changed 2/2026" },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "Priority Pass", detail: "unlimited visits, 2 free guests/visit" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "Priority Pass", detail: "4 visits/yr" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Centurion + Priority Pass + Delta Sky Club", detail: "1,550+ lounges; Sky Club 10 visits/yr" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null, detail: "Sky Club access eliminated Jan 2024" },
          hilton_aspire: { value: "Priority Pass", detail: "1,200+ lounges" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: "2 United Club passes/yr" },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Hotel status",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "IHG Platinum Elite" },
          amex_platinum: { value: "Hilton Gold + Marriott Gold" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Hilton Gold + Marriott Gold" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: "Hilton Diamond" },
          ihg_premier: { value: "IHG Platinum Elite" },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: "Discoverist" },
        },
      },
      {
        label: "Global Entry/TSA",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "$30/yr" },
          amex_platinum: { value: "$120/4yr" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "$120/4yr" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "$120/4yr" },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "$120/4yr" },
          capital_one_venture: { value: "$120/4yr" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "$100/4yr" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "$120/4yr" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: "$120/4yr" },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: "$120/4yr" },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "DashPass",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Included" },
          amex_platinum: { value: null },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Included" },
          chase_freedom_flex: { value: "6-mo trial", detail: "activate by 12/31/2027" },
          chase_freedom_unlimited: { value: "6-mo trial", detail: "activate by 12/31/2027" },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: "Included", detail: "+ $10/mo DoorDash credit" },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Uber One",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "Included" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Walmart+",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "Included" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "CLEAR+",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "$219/yr credit" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "$219/yr credit" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: "$219/yr credit" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Travel concierge",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Reserve Designer" },
          amex_platinum: { value: "Platinum Concierge" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Citi Concierge" },
          citi_strata_premier: { value: "Citi Concierge" },
          capital_one_venture_x: { value: "Visa Infinite Concierge" },
          capital_one_venture: { value: "Visa Signature Concierge" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Platinum Concierge" },
          apple_card: { value: null },
          capital_one_savor: { value: "Visa Signature Concierge" },
          delta_platinum: { value: null },
          hilton_aspire: { value: "Concierge" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Amex Travel access",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "Yes", detail: "FHR + THC" },
          amex_gold: { value: "Yes" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Yes", detail: "FHR + THC" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Rental car status",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: null },
          amex_gold: { value: "Hertz Five Star", detail: "enrollment required" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "Hertz President's Circle" },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
    ],
  },
  {
    sectionId: "protections",
    label: "Protections & Insurance",
    tracked: false,
    rows: [
      {
        label: "Auto rental CDW",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Primary" },
          amex_platinum: { value: "Secondary" },
          amex_gold: { value: "Secondary" },
          amex_blue_cash_preferred: { value: "Secondary" },
          chase_sapphire_preferred: { value: "Primary" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Primary" },
          citi_strata_premier: { value: "Secondary", detail: "primary internationally" },
          capital_one_venture_x: { value: "Primary" },
          capital_one_venture: { value: "Primary" },
          robinhood_gold: { value: "Primary" },
          bilt_palladium: { value: "Primary" },
          amex_blue_cash_everyday: { value: "Secondary" },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: "Secondary", detail: "$50K, 15 days domestic" },
          wells_fargo_autograph_journey: { value: "Primary", detail: "international; secondary domestic" },
          amex_business_platinum: { value: "Secondary" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Secondary" },
          hilton_aspire: { value: "Secondary" },
          ihg_premier: { value: "Secondary", detail: "via Visa" },
          ink_business_preferred: { value: "Primary", detail: "unique: primary CDW!" },
          southwest_priority: { value: null },
          united_explorer: { value: "Secondary", detail: "via Visa" },
          world_of_hyatt: { value: "Secondary", detail: "via Visa" },
        },
      },
      {
        label: "Trip cancellation",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: "Yes", detail: "$1,500/person" },
          chase_freedom_unlimited: { value: "Yes", detail: "$1,500/person" },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: "Yes", detail: "$5K/person" },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: null },
          robinhood_gold: { value: "Yes", detail: "$2K/person" },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "Yes", detail: "$2K/person" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: "Yes", detail: "$15K/person" },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null, detail: "trip delay only" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: "Yes" },
          ink_business_preferred: { value: "Yes" },
          southwest_priority: { value: null },
          united_explorer: { value: "Yes" },
          world_of_hyatt: { value: "Yes" },
        },
      },
      {
        label: "Trip delay reimburse",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: "Yes", detail: "$300, 12+ hr, 2 claims/12mo" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: "Yes", detail: "$500/occurrence" },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: "Yes", detail: "$500/person" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "Yes", detail: "$300/trip" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "Yes", detail: "$300 if >12hrs" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Yes" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: "Yes" },
          ink_business_preferred: { value: "Yes" },
          southwest_priority: { value: null },
          united_explorer: { value: "Yes" },
          world_of_hyatt: { value: "Yes" },
        },
      },
      {
        label: "Lost luggage reimburse",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: "Yes", detail: "$1,250 carry-on/$500 checked" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: "Yes", detail: "$3,000/bag" },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: "Yes", detail: "$3,000/passenger" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: "Yes", detail: "$3,000/trip" },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: "Yes", detail: "$3,000/trip" },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Yes" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: "Yes" },
          ink_business_preferred: { value: "Yes" },
          southwest_priority: { value: null },
          united_explorer: { value: "Yes" },
          world_of_hyatt: { value: "Yes" },
        },
      },
      {
        label: "Cell phone protection",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: null },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: null },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: "Yes", detail: "$800/claim; ends 9/20/2026" },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "Yes", detail: "$800/claim, 2 claims/yr" },
          capital_one_venture: { value: "Yes", detail: "$800/claim, 2 claims/yr" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "Yes", detail: "$800/claim, 2 claims/yr" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: "Yes", detail: "$600/claim, 2 claims/yr" },
          wells_fargo_autograph_journey: { value: "Yes", detail: "$1,000/claim, 2 claims/yr" },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: "Yes", detail: "$800/claim, 2 claims/yr, $50 deductible" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: "Yes", detail: "$1,000/claim, 3 claims/yr, $100 deductible" },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Purchase protection",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: "Yes" },
          amex_blue_cash_preferred: { value: "Yes" },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: "Yes" },
          chase_freedom_unlimited: { value: "Yes" },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: "Yes" },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: "Yes" },
          robinhood_gold: { value: "Yes" },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: "Yes", detail: "$1K/occurrence" },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Yes" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: "Yes" },
          ink_business_preferred: { value: "Yes" },
          southwest_priority: { value: null },
          united_explorer: { value: "Yes" },
          world_of_hyatt: { value: "Yes" },
        },
      },
      {
        label: "Extended warranty",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: "Yes" },
          amex_blue_cash_preferred: { value: "Yes" },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: "Yes" },
          chase_freedom_unlimited: { value: "Yes" },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: "Yes" },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: "Yes" },
          robinhood_gold: { value: "Yes" },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: "Yes" },
          citi_custom_cash: { value: "Yes", detail: "24mo, $10K/item" },
          citi_double_cash: { value: "Yes", detail: "24mo, $10K/item" },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Yes" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: "Yes" },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Return protection",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes", detail: "$500/item, $1,000/yr" },
          amex_platinum: { value: "Yes" },
          amex_gold: { value: null, detail: "removed Jan 2020" },
          amex_blue_cash_preferred: { value: "Yes" },
          chase_sapphire_preferred: { value: null },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: null },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: "Yes" },
          capital_one_venture: { value: null },
          robinhood_gold: { value: "Yes" },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: "Yes" },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: "Yes" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: "Yes" },
          hilton_aspire: { value: "Yes" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
      {
        label: "Roadside assistance",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Yes" },
          amex_platinum: { value: null, detail: "discontinued Jan 2020; Global Assist only" },
          amex_gold: { value: null, detail: "discontinued Jan 2020; Global Assist only" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Yes" },
          chase_freedom_flex: { value: null },
          chase_freedom_unlimited: { value: null },
          citi_strata_elite: { value: "Yes" },
          citi_strata_premier: { value: null },
          capital_one_venture_x: { value: null },
          capital_one_venture: { value: null },
          robinhood_gold: { value: null },
          bilt_palladium: { value: null },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null },
          citi_double_cash: { value: null },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: null },
          amex_business_platinum: { value: null, detail: "discontinued Jan 2020; Global Assist only" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null, detail: "discontinued Jan 2020; Global Assist only" },
          hilton_aspire: { value: null, detail: "discontinued Jan 2020; Global Assist only" },
          ihg_premier: { value: null },
          ink_business_preferred: { value: null },
          southwest_priority: { value: null },
          united_explorer: { value: null },
          world_of_hyatt: { value: null },
        },
      },
    ],
  },
  {
    sectionId: "transfer_partners",
    label: "Transfer Partners",
    tracked: false,
    rows: [
      {
        label: "Hotel partners",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "Hyatt, IHG, Marriott" },
          amex_platinum: { value: "Hilton, Marriott, Choice" },
          amex_gold: { value: "Hilton, Choice" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "Hyatt, IHG, Marriott" },
          chase_freedom_flex: { value: "Hyatt, IHG, Marriott", detail: "via CSR/CSP" },
          chase_freedom_unlimited: { value: "Hyatt, IHG, Marriott", detail: "via CSR/CSP" },
          citi_strata_elite: { value: "Choice (1:2), Wyndham" },
          citi_strata_premier: { value: "Choice (1:2), Wyndham, Hyatt, Marriott" },
          capital_one_venture_x: { value: "Accor, Choice, Wyndham, I Prefer" },
          capital_one_venture: { value: "Marriott, Hyatt, IHG" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "Hyatt, Marriott, Hilton, IHG, Wyndham, Accor (3:2), I Prefer (1:2)", detail: "7 hotel programs" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null, detail: "via Strata Premier/Elite" },
          citi_double_cash: { value: "Choice, Wyndham", detail: "limited without Strata" },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: "Choice (1:2), Wyndham" },
          amex_business_platinum: { value: "Hilton, Marriott, Choice" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null },
          hilton_aspire: { value: null, detail: "Hilton-only program" },
          ihg_premier: { value: null, detail: "IHG-only program" },
          ink_business_preferred: { value: "Hyatt, IHG, Marriott", detail: "via Chase UR" },
          southwest_priority: { value: null },
          united_explorer: { value: null, detail: "United-only program" },
          world_of_hyatt: { value: null, detail: "Hyatt-only program" },
        },
      },
      {
        label: "Airline partners",
        tracked: false,
        cards: {
          chase_sapphire_reserve: { value: "United, SW, BA, Air France" },
          amex_platinum: { value: "Delta, JetBlue, ANA, Singapore, Virgin Atlantic" },
          amex_gold: { value: "Delta, JetBlue, ANA, Singapore" },
          amex_blue_cash_preferred: { value: null },
          chase_sapphire_preferred: { value: "United, SW, BA, Air France" },
          chase_freedom_flex: { value: "United, SW, BA, Air France", detail: "via CSR/CSP" },
          chase_freedom_unlimited: { value: "United, SW, BA, Air France", detail: "via CSR/CSP" },
          citi_strata_elite: { value: "AA, JetBlue, Singapore, Turkish, Qatar" },
          citi_strata_premier: { value: "AA, JetBlue, Singapore, Turkish, Emirates", detail: "22 partners" },
          capital_one_venture_x: { value: "Avianca, Aeroplan, BA, Air France, Turkish", detail: "18 airline partners" },
          capital_one_venture: { value: "Avianca, Aeroplan, BA, Air France, Turkish", detail: "22+ partners" },
          robinhood_gold: { value: null },
          bilt_palladium: { value: "United, AA, Aeroplan, Emirates, Singapore, JAL", detail: "17+ airline partners" },
          amex_blue_cash_everyday: { value: null },
          citi_custom_cash: { value: null, detail: "via Strata Premier/Elite" },
          citi_double_cash: { value: "JetBlue (1:0.8)", detail: "limited without Strata" },
          discover_it_cash_back: { value: null },
          us_bank_altitude_connect: { value: null },
          wells_fargo_active_cash: { value: null },
          wells_fargo_autograph_journey: { value: "Flying Blue, Avianca, BA, Iberia, Virgin Atlantic, JetBlue, Cathay Pacific", detail: "8 airline partners at 1:1" },
          amex_business_platinum: { value: "Delta, ANA, Singapore, Virgin Atlantic", detail: "20+ airline partners via MR" },
          apple_card: { value: null },
          capital_one_savor: { value: null },
          delta_platinum: { value: null, detail: "Delta SkyMiles only" },
          hilton_aspire: { value: null, detail: "Hilton points only" },
          ihg_premier: { value: null, detail: "IHG points only" },
          ink_business_preferred: { value: "United, SW, BA, Air France", detail: "via Chase UR" },
          southwest_priority: { value: null, detail: "Southwest RR only" },
          united_explorer: { value: null, detail: "United MileagePlus only" },
          world_of_hyatt: { value: null, detail: "Hyatt points only" },
        },
      },
    ],
  },
];

export interface CardReferenceLink {
  label: string;
  url: string;
}

export interface CardReferenceLinks {
  cardId: string;
  cardName: string;
  links: CardReferenceLink[];
}

export const CARD_REFERENCE_LINKS: CardReferenceLinks[] = [
  {
    cardId: "chase_sapphire_reserve",
    cardName: "Chase Sapphire Reserve",
    links: [
      { label: "Card benefits overview", url: "https://www.chase.com/personal/credit-cards/sapphire/reserve" },
      { label: "Rewards & earn rates", url: "https://www.chase.com/personal/credit-cards/sapphire/reserve/earn-rewards" },
      { label: "Transfer partners", url: "https://ultimaterewardspoints.chase.com/transfer-partners" },
      { label: "Insurance & protections", url: "https://www.chase.com/personal/credit-cards/sapphire/reserve/card-benefits" },
    ],
  },
  {
    cardId: "amex_platinum",
    cardName: "Amex Platinum",
    links: [
      { label: "Card benefits overview", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/" },
      { label: "Rewards & earn rates", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/rewards" },
      { label: "Transfer partners", url: "https://global.americanexpress.com/rewards/transfer" },
      { label: "Insurance & protections", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/benefits" },
    ],
  },
  {
    cardId: "amex_gold",
    cardName: "Amex Gold",
    links: [
      { label: "Card benefits overview", url: "https://www.americanexpress.com/us/credit-cards/card-application/apply/gold-card" },
      { label: "Rewards & earn rates", url: "https://www.americanexpress.com/us/credit-cards/card-application/apply/gold-card/rewards" },
      { label: "Transfer partners", url: "https://global.americanexpress.com/rewards/transfer" },
      { label: "Insurance & protections", url: "https://www.americanexpress.com/us/credit-cards/card-application/apply/gold-card/benefits" },
    ],
  },
  {
    cardId: "amex_blue_cash_preferred",
    cardName: "Amex Blue Cash Preferred",
    links: [
      { label: "Card overview", url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/" },
      { label: "Rewards & earn rates", url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/rewards" },
    ],
  },
  {
    cardId: "chase_sapphire_preferred",
    cardName: "Chase Sapphire Preferred",
    links: [
      { label: "Card benefits overview", url: "https://www.chase.com/personal/credit-cards/sapphire/preferred" },
      { label: "Rewards & earn rates", url: "https://www.chase.com/personal/credit-cards/sapphire/preferred/earn-rewards" },
      { label: "Transfer partners", url: "https://ultimaterewardspoints.chase.com/transfer-partners" },
      { label: "Insurance & protections", url: "https://www.chase.com/personal/credit-cards/sapphire/preferred/card-benefits" },
    ],
  },
  {
    cardId: "chase_freedom_flex",
    cardName: "Chase Freedom Flex",
    links: [
      { label: "Card benefits overview", url: "https://creditcards.chase.com/freedom-credit-cards/flex" },
      { label: "Rewards & earn rates", url: "https://creditcards.chase.com/freedom-credit-cards/flex/earn-rewards" },
    ],
  },
  {
    cardId: "chase_freedom_unlimited",
    cardName: "Chase Freedom Unlimited",
    links: [
      { label: "Card benefits overview", url: "https://creditcards.chase.com/freedom-credit-cards/unlimited" },
      { label: "Rewards & earn rates", url: "https://creditcards.chase.com/freedom-credit-cards/unlimited/earn-rewards" },
    ],
  },
  {
    cardId: "citi_strata_elite",
    cardName: "Citi Strata Elite",
    links: [
      { label: "Card benefits overview", url: "https://www.citi.com/credit-cards/citi-strata-elite-credit-card" },
      { label: "Transfer partners", url: "https://www.thankyou.com/cms/thankyou/program/transfer.page" },
    ],
  },
  {
    cardId: "citi_strata_premier",
    cardName: "Citi Strata Premier",
    links: [
      { label: "Card benefits overview", url: "https://www.citi.com/credit-cards/citi-strata-premier-credit-card" },
      { label: "Transfer partners", url: "https://www.thankyou.com/cms/thankyou/program/transfer.page" },
    ],
  },
  {
    cardId: "capital_one_venture_x",
    cardName: "Capital One Venture X",
    links: [
      { label: "Card overview", url: "https://www.capitalone.com/credit-cards/venture-x/" },
      { label: "Rewards & benefits", url: "https://www.capitalone.com/credit-cards/venture-x/#benefits" },
    ],
  },
  {
    cardId: "capital_one_venture",
    cardName: "Capital One Venture",
    links: [
      { label: "Card overview", url: "https://www.capitalone.com/credit-cards/venture/" },
      { label: "Rewards & benefits", url: "https://www.capitalone.com/credit-cards/venture/#benefits" },
    ],
  },
  {
    cardId: "robinhood_gold",
    cardName: "Robinhood Gold Card",
    links: [
      { label: "Card overview", url: "https://robinhood.com/creditcard/" },
    ],
  },
  {
    cardId: "bilt_palladium",
    cardName: "Bilt Palladium Card",
    links: [
      { label: "Card overview", url: "https://www.bilt.com/card/palladium" },
      { label: "Bilt Rewards", url: "https://www.bilt.com" },
      { label: "Bilt Travel", url: "https://www.bilt.com/travel" },
    ],
  },
  {
    cardId: "amex_blue_cash_everyday",
    cardName: "Amex Blue Cash Everyday",
    links: [
      { label: "Card overview", url: "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/" },
    ],
  },
  {
    cardId: "citi_custom_cash",
    cardName: "Citi Custom Cash",
    links: [
      { label: "Card overview", url: "https://www.citi.com/credit-cards/citi-custom-cash-credit-card" },
    ],
  },
  {
    cardId: "citi_double_cash",
    cardName: "Citi Double Cash",
    links: [
      { label: "Card overview", url: "https://www.citi.com/credit-cards/citi-double-cash-credit-card" },
    ],
  },
  {
    cardId: "discover_it_cash_back",
    cardName: "Discover it Cash Back",
    links: [
      { label: "Card overview", url: "https://www.discover.com/credit-cards/cash-back/it-card.html" },
    ],
  },
  {
    cardId: "us_bank_altitude_connect",
    cardName: "US Bank Altitude Connect",
    links: [
      { label: "Card overview", url: "https://www.usbank.com/credit-cards/altitude-connect-visa-signature-credit-card.html" },
    ],
  },
  {
    cardId: "wells_fargo_active_cash",
    cardName: "Wells Fargo Active Cash",
    links: [
      { label: "Card overview", url: "https://www.wellsfargo.com/credit-cards/active-cash/" },
    ],
  },
  {
    cardId: "wells_fargo_autograph_journey",
    cardName: "Wells Fargo Autograph Journey",
    links: [
      { label: "Card overview", url: "https://creditcards.wellsfargo.com/autograph-journey-visa-credit-card/" },
      { label: "Transfer partners", url: "https://www.wellsfargo.com/rewards/transfer-partners/" },
    ],
  },
  {
    cardId: "amex_business_platinum",
    cardName: "Amex Business Platinum",
    links: [
      { label: "Card overview", url: "https://www.americanexpress.com/us/credit-cards/business/business-credit-cards/amex-business-platinum/" },
    ],
  },
  {
    cardId: "apple_card",
    cardName: "Apple Card",
    links: [
      { label: "Card overview", url: "https://www.apple.com/apple-card/" },
    ],
  },
  {
    cardId: "capital_one_savor",
    cardName: "Capital One Savor",
    links: [
      { label: "Card overview", url: "https://www.capitalone.com/credit-cards/savor/" },
    ],
  },
  {
    cardId: "delta_platinum",
    cardName: "Delta SkyMiles Platinum Amex",
    links: [
      { label: "Card overview", url: "https://www.americanexpress.com/us/credit-cards/card/delta-skymiles-platinum/" },
    ],
  },
  {
    cardId: "hilton_aspire",
    cardName: "Hilton Honors Amex Aspire",
    links: [
      { label: "Card overview", url: "https://www.americanexpress.com/us/credit-cards/card/hilton-honors-aspire/" },
    ],
  },
  {
    cardId: "ihg_premier",
    cardName: "IHG One Rewards Premier",
    links: [
      { label: "Card overview", url: "https://creditcards.chase.com/travel-credit-cards/ihg-one-rewards-premier" },
    ],
  },
  {
    cardId: "ink_business_preferred",
    cardName: "Chase Ink Business Preferred",
    links: [
      { label: "Card overview", url: "https://creditcards.chase.com/business-credit-cards/ink/business-preferred" },
    ],
  },
  {
    cardId: "southwest_priority",
    cardName: "Southwest Rapid Rewards Priority",
    links: [
      { label: "Card overview", url: "https://creditcards.chase.com/travel-credit-cards/southwest/priority" },
    ],
  },
  {
    cardId: "united_explorer",
    cardName: "United Explorer",
    links: [
      { label: "Card overview", url: "https://creditcards.chase.com/travel-credit-cards/united/explorer" },
    ],
  },
  {
    cardId: "world_of_hyatt",
    cardName: "World of Hyatt Chase",
    links: [
      { label: "Card overview", url: "https://creditcards.chase.com/travel-credit-cards/world-of-hyatt" },
    ],
  },
];
