import type { BenefitDetails, CardDefinition } from "@/lib/types";

const uberCashDetails: BenefitDetails = {
  description:
    "Up to $200/year in Uber Cash: $15/month (Jan–Nov) and $35 in December. Uber Cash can be used for Uber rides, Uber Eats orders, and other Uber services. Credits are automatically added to your connected Uber account each month.",
  howToUse: [
    "Open the Uber app and go to Wallet",
    "Add your Platinum Card as the payment method",
    "Link your Amex and Uber accounts via amex.com/uber or the Amex app",
    "Uber Cash is automatically added at the start of each month",
    "Use for rides, Uber Eats, or grocery delivery",
  ],
  links: [
    { label: "Link your accounts", url: "https://www.americanexpress.com/en-us/benefits/uber/" },
    { label: "Uber", url: "https://www.uber.com" },
    { label: "Learn More", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/" },
  ],
};

const uberOneDetails: BenefitDetails = {
  description:
    "Complimentary Uber One membership (normally $9.99/mo). Includes $0 delivery fees, up to 10% off eligible Uber Eats orders, and 5% off eligible Uber rides. Must link Amex and Uber accounts.",
  howToUse: [
    "Link your Amex and Uber accounts via amex.com/uber",
    "Uber One membership is automatically activated",
    "Benefits apply to eligible Uber rides and Uber Eats orders",
  ],
  links: [
    { label: "Link your accounts", url: "https://www.americanexpress.com/en-us/benefits/uber/" },
    { label: "Uber One", url: "https://www.uber.com/us/en/u/uber-one/" },
  ],
};

const digitalEntertainmentDetails: BenefitDetails = {
  description:
    "Up to $25/month in statement credits for eligible digital entertainment subscriptions: Disney+, Hulu, ESPN+, The New York Times, The Wall Street Journal, YouTube Premium, SiriusXM, Audible, Peacock, and more. Must enroll before first purchase.",
  howToUse: [
    "Open the Amex app or log in to americanexpress.com",
    "Go to Benefits → find the Digital Entertainment Credit",
    "Tap to enroll in the benefit",
    "Subscribe to an eligible streaming service using your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
    { label: "Eligible services", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/digital-entertainment-credit/" },
    { label: "Learn More", url: "https://www.americanexpress.com/us/credit-cards/card/platinum/" },
  ],
};

const walmartPlusDetails: BenefitDetails = {
  description:
    "Up to $12.95/month in statement credits covering the cost of a Walmart+ membership. Includes free delivery from your local store, free shipping with no minimum, member prices on fuel, and more.",
  howToUse: [
    "Open the Amex app or log in to americanexpress.com",
    "Go to Benefits → find the Walmart+ Credit",
    "Tap to enroll in the benefit",
    "Sign up for Walmart+ using your Platinum Card",
    "Statement credit posts automatically after the monthly charge",
  ],
  links: [
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
    { label: "Walmart+", url: "https://www.walmart.com/plus" },
  ],
};

const resyCreditDetails: BenefitDetails = {
  description:
    "Up to $100 per quarter in statement credits for purchases made at Resy restaurants or on Resy.com/app. Must enroll before first purchase. Unused credit in one quarter does NOT carry to the next.",
  howToUse: [
    "Open the Amex app or log in to americanexpress.com",
    "Go to Benefits → find the Resy Credit",
    "Tap to enroll in the benefit",
    "Dine at a Resy-affiliated restaurant and pay with your Platinum Card, or make a purchase on Resy.com/app",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "Resy", url: "https://resy.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const lululemonDetails: BenefitDetails = {
  description:
    "Up to $75 per quarter in statement credits for purchases at lululemon (in-store or online). Must enroll before first purchase. Unused credit in one quarter does NOT carry to the next.",
  howToUse: [
    "Open the Amex app or log in to americanexpress.com",
    "Go to Benefits → find the lululemon Credit",
    "Tap to enroll in the benefit",
    "Shop at any lululemon location or on lululemon.com using your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "lululemon", url: "https://www.lululemon.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const hotelCreditDetails: BenefitDetails = {
  description:
    "Up to $300 per half-year ($600 annual total) in statement credits for prepaid hotel stays booked through The Hotel Collection or Fine Hotels + Resorts via AmexTravel.com. Two-night minimum stay required.",
  howToUse: [
    "Go to AmexTravel.com or use the Amex app",
    "Search for hotels and look for Fine Hotels + Resorts or The Hotel Collection properties",
    "Book a prepaid stay of at least 2 nights using your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "AmexTravel.com", url: "https://travel.americanexpress.com" },
    { label: "Fine Hotels + Resorts", url: "https://www.americanexpress.com/en-us/travel/fine-hotels-resorts/" },
  ],
};

const saksCreditDetails: BenefitDetails = {
  description:
    "Up to $50 per half-year ($100 annual total) in statement credits for purchases at Saks Fifth Avenue stores or saks.com. Must enroll before first purchase.",
  howToUse: [
    "Open the Amex app or log in to americanexpress.com",
    "Go to Benefits → find the Saks Fifth Avenue Credit",
    "Tap to enroll in the benefit",
    "Shop at Saks Fifth Avenue (in-store or online) using your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "Saks Fifth Avenue", url: "https://www.saksfifthavenue.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const airlineFeeCreditDetails: BenefitDetails = {
  description:
    "Up to $200/year in statement credits for incidental fees charged by your selected qualifying airline. Covers baggage fees, seat upgrades, in-flight purchases, and other incidental charges. Does NOT cover airfare. Must select one airline per calendar year.",
  howToUse: [
    "Log in to americanexpress.com",
    "Go to Benefits → Airline Fee Credit",
    "Select your preferred qualifying airline for the calendar year",
    "Pay for incidental fees (bags, seats, etc.) with your Platinum Card on that airline",
    "Statement credit posts automatically",
  ],
  links: [
    { label: "Select your airline", url: "https://global.americanexpress.com/card-benefits/detail/airline-fee/platinum" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const equinoxDetails: BenefitDetails = {
  description:
    "Up to $300/year ($25/month) in statement credits toward an Equinox+ digital fitness membership or eligible Equinox club membership fees. Must pay with your Platinum Card.",
  howToUse: [
    "Sign up for Equinox or Equinox+ using your Platinum Card",
    "Statement credits of up to $25/month post automatically",
    "Applies to Equinox club dues and Equinox+ digital membership",
  ],
  links: [
    { label: "Equinox", url: "https://www.equinox.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const clearDetails: BenefitDetails = {
  description:
    "Up to $209/year in statement credits covering a CLEAR Plus membership (normally $189/yr, may vary). CLEAR provides expedited security screening at 50+ airports and select stadiums.",
  howToUse: [
    "Sign up for CLEAR Plus at clearme.com or at an airport CLEAR pod",
    "Pay with your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "CLEAR", url: "https://www.clearme.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

const globalEntryDetails: BenefitDetails = {
  description:
    "Up to $120 statement credit every 4 years for Global Entry or TSA PreCheck application fees. Applies to the application fee only.",
  howToUse: [
    "Apply for Global Entry ($120) or TSA PreCheck ($85) through the official government sites",
    "Pay the application fee with your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "Global Entry", url: "https://www.cbp.gov/travel/trusted-traveler-programs/global-entry" },
    { label: "TSA PreCheck", url: "https://www.tsa.gov/precheck" },
  ],
};

const ouraDetails: BenefitDetails = {
  description:
    "Up to $200/year in statement credits toward an Oura Ring purchase or Oura membership fees. Must pay with your Platinum Card.",
  howToUse: [
    "Purchase an Oura Ring or pay for Oura membership using your Platinum Card",
    "Statement credit posts automatically after the charge",
  ],
  links: [
    { label: "Oura", url: "https://ouraring.com" },
    { label: "Amex Benefits", url: "https://www.americanexpress.com/en-us/benefits/discover/" },
  ],
};

export const amexPlatinum: CardDefinition = {
  id: "amex_platinum",
  name: "American Express\u00AE Platinum Card",
  issuer: "amex",
  network: "amex",
  annualFee: 695,
  feeDescriptor: "annual membership fee",
  imageUrl: null,
  isActive: true,
  benefits: [
    // ── Quarterly Resy Credits ($100/quarter × 4) ──
    {
      id: "plat_resy_credit_q1",
      cardId: "amex_platinum",
      name: "Resy Credit (Q1)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 100,
      cycle: "quarterly_q1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["resy"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: true,
      priority: 10,
      description: "Up to $100 in statement credits for Resy dining (Jan–Mar).",
      notes: "Must enroll before first purchase. Reservation through Resy not required.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: resyCreditDetails,
    },
    {
      id: "plat_resy_credit_q2",
      cardId: "amex_platinum",
      name: "Resy Credit (Q2)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 100,
      cycle: "quarterly_q2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["resy"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: true,
      priority: 10,
      description: "Up to $100 in statement credits for Resy dining (Apr–Jun).",
      notes: "Must enroll before first purchase. Reservation through Resy not required.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: resyCreditDetails,
    },
    {
      id: "plat_resy_credit_q3",
      cardId: "amex_platinum",
      name: "Resy Credit (Q3)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 100,
      cycle: "quarterly_q3",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["resy"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: true,
      priority: 10,
      description: "Up to $100 in statement credits for Resy dining (Jul–Sep).",
      notes: "Must enroll before first purchase. Reservation through Resy not required.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: resyCreditDetails,
    },
    {
      id: "plat_resy_credit_q4",
      cardId: "amex_platinum",
      name: "Resy Credit (Q4)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 100,
      cycle: "quarterly_q4",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["resy"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: true,
      priority: 10,
      description: "Up to $100 in statement credits for Resy dining (Oct–Dec).",
      notes: "Must enroll before first purchase. Reservation through Resy not required.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: resyCreditDetails,
    },

    // ── Quarterly lululemon Credits ($75/quarter × 4) ──
    {
      id: "plat_lululemon_credit_q1",
      cardId: "amex_platinum",
      name: "lululemon Credit (Q1)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 75,
      cycle: "quarterly_q1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["lululemon"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $75 in statement credits at lululemon (Jan–Mar).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: lululemonDetails,
    },
    {
      id: "plat_lululemon_credit_q2",
      cardId: "amex_platinum",
      name: "lululemon Credit (Q2)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 75,
      cycle: "quarterly_q2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["lululemon"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $75 in statement credits at lululemon (Apr–Jun).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: lululemonDetails,
    },
    {
      id: "plat_lululemon_credit_q3",
      cardId: "amex_platinum",
      name: "lululemon Credit (Q3)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 75,
      cycle: "quarterly_q3",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["lululemon"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $75 in statement credits at lululemon (Jul–Sep).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: lululemonDetails,
    },
    {
      id: "plat_lululemon_credit_q4",
      cardId: "amex_platinum",
      name: "lululemon Credit (Q4)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 75,
      cycle: "quarterly_q4",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["lululemon"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $75 in statement credits at lululemon (Oct–Dec).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: lululemonDetails,
    },

    // ── Semi-annual Hotel Credits ($300/half × 2) ──
    {
      id: "plat_hotel_credit_h1",
      cardId: "amex_platinum",
      name: "Hotel Credit (H1)",
      icon: "Hotel",
      category: "travel",
      type: "credit",
      creditAmount: 300,
      cycle: "biannual_h1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["fine hotels", "hotel collection", "amextravel", "amex travel"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 15,
      description: "Up to $300 in hotel credits via FHR/THC on AmexTravel.com (Jan–Jun).",
      notes: "Two-night minimum stay required. Book through AmexTravel.com.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: hotelCreditDetails,
    },
    {
      id: "plat_hotel_credit_h2",
      cardId: "amex_platinum",
      name: "Hotel Credit (H2)",
      icon: "Hotel",
      category: "travel",
      type: "credit",
      creditAmount: 300,
      cycle: "biannual_h2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["fine hotels", "hotel collection", "amextravel", "amex travel"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 15,
      description: "Up to $300 in hotel credits via FHR/THC on AmexTravel.com (Jul–Dec).",
      notes: "Two-night minimum stay required. Book through AmexTravel.com.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: hotelCreditDetails,
    },

    // ── Semi-annual Saks Credits ($50/half × 2) ──
    {
      id: "plat_saks_h1",
      cardId: "amex_platinum",
      name: "Saks Fifth Avenue Credit (H1)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 50,
      cycle: "biannual_h1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["saks fifth avenue", "saks", "saks.com"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $50 at Saks Fifth Avenue (Jan–Jun).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: saksCreditDetails,
    },
    {
      id: "plat_saks_h2",
      cardId: "amex_platinum",
      name: "Saks Fifth Avenue Credit (H2)",
      icon: "ShoppingBag",
      category: "shopping",
      type: "credit",
      creditAmount: 50,
      cycle: "biannual_h2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["saks fifth avenue", "saks", "saks.com"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $50 at Saks Fifth Avenue (Jul–Dec).",
      notes: "Must enroll before first purchase.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: saksCreditDetails,
    },

    // ── Monthly Benefits ──
    {
      id: "plat_digital_entertainment",
      cardId: "amex_platinum",
      name: "Digital Entertainment Credit",
      icon: "Tv",
      category: "entertainment",
      type: "credit",
      creditAmount: 25,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: [
        "disney+", "disneyplus", "hulu", "espn+", "espnplus",
        "new york times", "nytimes", "wall street journal", "wsj",
        "youtube premium", "youtube music", "sirius", "siriusxm",
        "audible", "peacock",
      ],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $25/month for eligible digital entertainment subscriptions.",
      notes: "Must enroll before first purchase. Eligible services include Disney+, Hulu, ESPN+, NYT, WSJ, YouTube Premium, SiriusXM, Audible, Peacock.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: digitalEntertainmentDetails,
    },
    {
      id: "plat_uber_cash",
      cardId: "amex_platinum",
      name: "Uber Cash",
      icon: "Car",
      category: "transport",
      type: "credit",
      creditAmount: 15,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["uber"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $15/month in Uber Cash (Jan–Nov).",
      notes: "Uber Cash auto-deposits monthly. Use for rides, Uber Eats, or grocery delivery.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: uberCashDetails,
      brandSlug: "uber",
      activeMonths: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], // Jan–Nov
    },
    {
      id: "plat_uber_cash_dec",
      cardId: "amex_platinum",
      name: "Uber Cash",
      icon: "Car",
      category: "transport",
      type: "credit",
      creditAmount: 35,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["uber"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 19,
      description: "Up to $35 in Uber Cash for December.",
      notes: "December bonus — higher Uber Cash allowance.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: uberCashDetails,
      brandSlug: "uber",
      activeMonths: [11], // Dec only
    },
    {
      id: "plat_walmart_plus",
      cardId: "amex_platinum",
      name: "Walmart+ Credit",
      icon: "ShoppingCart",
      category: "shopping",
      type: "credit",
      creditAmount: 12.95,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["walmart+", "walmart plus", "walmart"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description: "Up to $12.95/month covering Walmart+ membership.",
      notes: "Must enroll before first purchase. Covers monthly Walmart+ subscription fee.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: walmartPlusDetails,
    },

    // ── Annual Calendar Benefits ──
    {
      id: "plat_uber_one",
      cardId: "amex_platinum",
      name: "Uber One Membership",
      icon: "Car",
      category: "transport",
      type: "subscription",
      creditAmount: 120,
      cycle: "annual_calendar",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["uber"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: true,
      priority: 25,
      description: "Complimentary Uber One membership (valued at ~$120/year).",
      notes: "Must link Amex and Uber accounts. Includes $0 delivery fees and discounts on rides.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: uberOneDetails,
      brandSlug: "uber",
    },
    {
      id: "plat_airline_fee_credit",
      cardId: "amex_platinum",
      name: "Airline Fee Credit",
      icon: "Plane",
      category: "travel",
      type: "credit",
      creditAmount: 200,
      cycle: "annual_calendar",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: [],
      plaidCategories: ["TRAVEL_FLIGHTS"],
      autoMatchable: false,
      requiresActivation: true,
      priority: 30,
      description: "Up to $200/year for incidental airline fees on your selected airline.",
      notes: "Must select one airline per calendar year. Covers bags, seat upgrades, in-flight purchases — NOT airfare.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: airlineFeeCreditDetails,
    },
    {
      id: "plat_equinox",
      cardId: "amex_platinum",
      name: "Equinox Credit",
      icon: "Dumbbell",
      category: "fitness",
      type: "credit",
      creditAmount: 300,
      cycle: "annual_calendar",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["equinox"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $300/year toward Equinox membership.",
      notes: "Applies to Equinox club dues or Equinox+ digital membership.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: equinoxDetails,
    },
    {
      id: "plat_clear",
      cardId: "amex_platinum",
      name: "CLEAR+ Credit",
      icon: "Shield",
      category: "travel",
      type: "credit",
      creditAmount: 209,
      cycle: "annual_calendar",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["clear", "clearme"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $209/year covering CLEAR Plus membership.",
      notes: "Covers the annual CLEAR Plus membership fee.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: clearDetails,
    },
    {
      id: "plat_oura",
      cardId: "amex_platinum",
      name: "Oura Ring Credit",
      icon: "Activity",
      category: "fitness",
      type: "credit",
      creditAmount: 200,
      cycle: "annual_calendar",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["oura"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $200/year toward Oura Ring or membership.",
      notes: "Covers Oura Ring purchase or ongoing membership fees.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: ouraDetails,
    },

    // ── Quadrennial ──
    {
      id: "plat_global_entry",
      cardId: "amex_platinum",
      name: "Global Entry / TSA PreCheck",
      icon: "Shield",
      category: "travel",
      type: "credit",
      creditAmount: 120,
      cycle: "quadrennial",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["global entry", "tsa precheck", "tsa pre"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $120 every 4 years for Global Entry or TSA PreCheck.",
      notes: "Covers application fee only.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
      details: globalEntryDetails,
    },
  ],
};
