import type { CardDefinition } from "@/lib/types";

export const chaseSapphireReserve: CardDefinition = {
  id: "chase_sapphire_reserve",
  name: "Chase Sapphire Reserve\u00AE",
  issuer: "chase",
  network: "visa",
  annualFee: 795,
  feeDescriptor: "annual membership fee",
  imageUrl: null,
  isActive: true,
  benefits: [
    // ── Travel Credit ($300/anniversary year) ──
    {
      id: "csr_travel",
      cardId: "chase_sapphire_reserve",
      name: "Travel Credit",
      icon: "Plane",
      category: "travel",
      type: "credit",
      creditAmount: 300,
      cycle: "annual_anniversary",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: [
        "airline",
        "hotel",
        "airbnb",
        "vrbo",
        "expedia",
        "booking.com",
        "hotels.com",
        "marriott",
        "hilton",
        "hyatt",
        "ihg",
        "united",
        "delta",
        "american airlines",
        "southwest",
        "jetblue",
        "alaska air",
        "spirit",
        "frontier",
        "uber",
        "lyft",
        "amtrak",
        "enterprise",
        "hertz",
        "avis",
        "national car",
        "turo",
        "cruise",
        "carnival",
        "royal caribbean",
        "parking",
        "toll",
      ],
      plaidCategories: ["TRAVEL"],
      autoMatchable: true,
      requiresActivation: false,
      priority: 30, // Lower priority — catch-all for travel; specific credits match first
      description:
        "Up to $300 in statement credits for travel purchases each cardmember anniversary year.",
      notes:
        "Accumulates until $300 is reached. Broad travel category including hotels, flights, car rentals, tolls, parking, transit.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── The Edit Hotel ($250 × 2 biannual) ──
    {
      id: "csr_edit_h1",
      cardId: "chase_sapphire_reserve",
      name: "The Edit Hotel Credit (H1)",
      icon: "Building",
      category: "travel",
      type: "credit",
      creditAmount: 250,
      cycle: "biannual_h1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["the edit"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 5,
      description:
        "Up to $250 in statement credits for bookings at The Edit hotel collection (Jan-Jun).",
      notes: "Must book through Chase Travel portal or The Edit website.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },
    {
      id: "csr_edit_h2",
      cardId: "chase_sapphire_reserve",
      name: "The Edit Hotel Credit (H2)",
      icon: "Building",
      category: "travel",
      type: "credit",
      creditAmount: 250,
      cycle: "biannual_h2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["the edit"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 5,
      description:
        "Up to $250 in statement credits for bookings at The Edit hotel collection (Jul-Dec).",
      notes: "Must book through Chase Travel portal or The Edit website.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── Exclusive Tables ($150 × 2 biannual) ──
    {
      id: "csr_dining_h1",
      cardId: "chase_sapphire_reserve",
      name: "Exclusive Tables Credit (H1)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 150,
      cycle: "biannual_h1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["exclusive tables", "chase dining"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 10,
      description:
        "Up to $150 in statement credits for Exclusive Tables dining experiences (Jan-Jun).",
      notes: "Must book through Chase Exclusive Tables program.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },
    {
      id: "csr_dining_h2",
      cardId: "chase_sapphire_reserve",
      name: "Exclusive Tables Credit (H2)",
      icon: "UtensilsCrossed",
      category: "dining",
      type: "credit",
      creditAmount: 150,
      cycle: "biannual_h2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["exclusive tables", "chase dining"],
      plaidCategories: [],
      autoMatchable: false,
      requiresActivation: false,
      priority: 10,
      description:
        "Up to $150 in statement credits for Exclusive Tables dining experiences (Jul-Dec).",
      notes: "Must book through Chase Exclusive Tables program.",
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── StubHub ($150 × 2 biannual) ──
    {
      id: "csr_stubhub_h1",
      cardId: "chase_sapphire_reserve",
      name: "StubHub Credit (H1)",
      icon: "Ticket",
      category: "entertainment",
      type: "credit",
      creditAmount: 150,
      cycle: "biannual_h1",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["stubhub"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 15,
      description:
        "Up to $150 in statement credits for StubHub purchases (Jan-Jun).",
      notes: "Must activate benefit first. Purchases on stubhub.com or app.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },
    {
      id: "csr_stubhub_h2",
      cardId: "chase_sapphire_reserve",
      name: "StubHub Credit (H2)",
      icon: "Ticket",
      category: "entertainment",
      type: "credit",
      creditAmount: 150,
      cycle: "biannual_h2",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["stubhub"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 15,
      description:
        "Up to $150 in statement credits for StubHub purchases (Jul-Dec).",
      notes: "Must activate benefit first. Purchases on stubhub.com or app.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── DoorDash (3 sub-credits, displayed as one $25/month group) ──
    {
      id: "csr_doordash_restaurant",
      cardId: "chase_sapphire_reserve",
      name: "DoorDash Restaurant Promo",
      icon: "Bike",
      category: "dining",
      type: "credit",
      creditAmount: 5,
      cycle: "monthly",
      carriesOver: true,
      maxCarryoverPeriods: 2,
      maxAccrued: 15,
      merchantPatterns: ["doordash"],
      plaidCategories: ["FOOD_AND_DRINK"],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description:
        "$5/month restaurant credit on DoorDash. Can accrue up to $15.",
      notes:
        "Applied at checkout on restaurant orders. Can accrue up to $15 over 3 months.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: "csr_doordash",
      displayGroupName: "DoorDash Credits",
      displayGroupIcon: "Bike",
    },
    {
      id: "csr_doordash_nonrestaurant_1",
      cardId: "chase_sapphire_reserve",
      name: "DoorDash Non-Restaurant Promo 1",
      icon: "Bike",
      category: "shopping",
      type: "credit",
      creditAmount: 10,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["doordash"],
      plaidCategories: ["FOOD_AND_DRINK"],
      autoMatchable: true,
      requiresActivation: true,
      priority: 21,
      description:
        "$10/month non-restaurant credit on DoorDash (grocery, convenience, retail).",
      notes: "Use-it-or-lose-it. Grocery, convenience, retail orders.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: "csr_doordash",
      displayGroupName: "DoorDash Credits",
      displayGroupIcon: "Bike",
    },
    {
      id: "csr_doordash_nonrestaurant_2",
      cardId: "chase_sapphire_reserve",
      name: "DoorDash Non-Restaurant Promo 2",
      icon: "Bike",
      category: "shopping",
      type: "credit",
      creditAmount: 10,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["doordash"],
      plaidCategories: ["FOOD_AND_DRINK"],
      autoMatchable: true,
      requiresActivation: true,
      priority: 22,
      description: "Second $10/month non-restaurant credit on DoorDash.",
      notes: "Same rules as Non-Restaurant Promo 1.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: "csr_doordash",
      displayGroupName: "DoorDash Credits",
      displayGroupIcon: "Bike",
    },

    // ── Lyft ($10/month) ──
    {
      id: "csr_lyft",
      cardId: "chase_sapphire_reserve",
      name: "Lyft Credit",
      icon: "Car",
      category: "transport",
      type: "credit",
      creditAmount: 10,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["lyft"],
      plaidCategories: ["TRANSPORTATION"],
      autoMatchable: true,
      requiresActivation: false,
      priority: 20,
      description: "Up to $10/month in Lyft ride credits.",
      notes: null,
      sunsetDate: "2027-09-30",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── Peloton ($10/month) ──
    {
      id: "csr_peloton",
      cardId: "chase_sapphire_reserve",
      name: "Peloton Credit",
      icon: "Dumbbell",
      category: "fitness",
      type: "credit",
      creditAmount: 10,
      cycle: "monthly",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["peloton"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 20,
      description:
        "Up to $10/month credit for Peloton membership or equipment.",
      notes: "Must activate benefit. Applies to Peloton App or All-Access.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── Global Entry / TSA PreCheck ($120/4 years) ──
    {
      id: "csr_global_entry",
      cardId: "chase_sapphire_reserve",
      name: "Global Entry / TSA PreCheck",
      icon: "ShieldCheck",
      category: "travel",
      type: "credit",
      creditAmount: 120,
      cycle: "quadrennial",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["global entry", "tsa", "goes"],
      plaidCategories: ["GOVERNMENT_AND_NON_PROFIT"],
      autoMatchable: true,
      requiresActivation: false,
      priority: 40,
      description:
        "Up to $120 credit for Global Entry or TSA PreCheck application fee every 4 years.",
      notes: null,
      sunsetDate: null,
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── Apple TV+ (subscription) ──
    {
      id: "csr_apple_tv",
      cardId: "chase_sapphire_reserve",
      name: "Apple TV+",
      icon: "Tv",
      category: "entertainment",
      type: "subscription",
      creditAmount: 0,
      cycle: "subscription",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["apple.com/bill", "apple tv"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 50,
      description: "Complimentary Apple TV+ subscription.",
      notes: "Must activate through Chase benefits portal.",
      sunsetDate: "2027-06-22",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── Apple Music (subscription) ──
    {
      id: "csr_apple_music",
      cardId: "chase_sapphire_reserve",
      name: "Apple Music",
      icon: "Music",
      category: "entertainment",
      type: "subscription",
      creditAmount: 0,
      cycle: "subscription",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["apple.com/bill", "apple music"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 50,
      description: "Complimentary Apple Music subscription (Individual plan).",
      notes: "Must activate through Chase benefits portal.",
      sunsetDate: "2027-06-22",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },

    // ── DashPass (subscription) ──
    {
      id: "csr_dashpass",
      cardId: "chase_sapphire_reserve",
      name: "DashPass by DoorDash",
      icon: "Bike",
      category: "subscription",
      type: "subscription",
      creditAmount: 0,
      cycle: "subscription",
      carriesOver: false,
      maxCarryoverPeriods: null,
      maxAccrued: null,
      merchantPatterns: ["doordash", "dashpass"],
      plaidCategories: [],
      autoMatchable: true,
      requiresActivation: true,
      priority: 50,
      description:
        "Complimentary DashPass membership for free delivery on DoorDash.",
      notes: "Must activate through DoorDash.",
      sunsetDate: "2027-12-31",
      sourceUrl: null,
      displayGroup: null,
      displayGroupName: null,
      displayGroupIcon: null,
    },
  ],
};
