import type { InsightCandidate } from "../types";
import type { GeneratorContext } from "./types";

/**
 * C0: First-Connect Value Snapshot
 * One-time insight generated after first card connect.
 * Sums all amountUsed from benefit usage to show existing value captured.
 */
export function generateC0(ctx: GeneratorContext): InsightCandidate[] {
  const { benefitUsages, annualFee, totalBenefitsCaptured, cardType } = ctx;

  // Dedup key: exactly once per card
  const dedupKey = `c0:${cardType}`;

  // C0 is generated by the orchestrator checking if this dedup key exists.
  // If it doesn't exist and we have transactions, generate it.
  // The orchestrator handles the dedup check, so we just produce the candidate.

  if (totalBenefitsCaptured <= 0) return [];

  const total = Math.round(totalBenefitsCaptured);
  const pctOfFee = annualFee > 0 ? Math.round((totalBenefitsCaptured / annualFee) * 100) : 0;

  // Determine how many months of history we have
  const usagePeriods = new Set(benefitUsages.map((u) => u.periodKey));
  const monthCount = usagePeriods.size;

  // Select template variant
  let templateKey: string;
  if (monthCount < 3) {
    templateKey = "c0_low_history";
  } else if (pctOfFee >= 50) {
    templateKey = "c0_strong";
  } else {
    templateKey = "c0_standard";
  }

  const templateVars: Record<string, string | number> = {
    total,
    pct_of_fee: pctOfFee,
    months: monthCount,
  };

  return [
    {
      category: "C0",
      benefitId: null,
      templateKey,
      templateVars,
      dedupKey,
      triggeredByTransactionId: null,
      periodStart: null,
      periodEnd: null,
      dollarAmount: total,
      daysRemaining: null,
      actionability: "plan_future",
      confidence: "exact_confirmed",
    },
  ];
}
